@baseUrl = http://localhost:3333

# @name create_event
POST {{baseUrl}}/events
Content-Type: application/json

{
  "title": "NLW Unite",
  "details": "Evento de programação",
  "maximumAttendees": 100
}

###

# @name register_for_event
POST {{baseUrl}}/events/9e9bd979-9d10-4915-b339-3786b1634f33/attendees
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com"
}

###

# @name get_event
GET {{baseUrl}}/events/9e9bd979-9d10-4915-b339-3786b1634f33
Content-Type: application/json

{}

###

# @name get_attendee_badge
GET {{baseUrl}}/attendees/10000/badge
Content-Type: application/json

{}

###

# @name check_in
GET {{baseUrl}}/attendees/10000/check-in
Content-Type: application/json

{}

###

# @name get_event_attendees
GET {{baseUrl}}/events/9e9bd979-9d10-4915-b339-3786b1634f33/attendees
Content-Type: application/json

{}